--元データ全削除 
DELETE FROM ms_deficiency_code;

--シーケンスリセット
SELECT SETVAL ('ms_deficiency_code_deficiency_code_id_seq', '1', false);

--Insert
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01101', 'Cargo Ship Safety Equipment (including exemption)', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01102', 'Cargo  Ship Safety Construction (including exempt.) ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01103', 'Passenger Ship Safety (including exemption) ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01104', 'Cargo Ship Safety Radio  (including exemption) ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01105', 'Cargo Ship Safety (including exemption) ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01106', 'Document of Compliance (DoC/ ISM) ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01107', 'Safety Mana gement Certificate (SMC/ ISM) ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01108', 'Load Lines (including Exemption) ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01109', 'Decision-Support System for Masters on Pass. Ships  ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01110', 'Authorization for grain carriage ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01111', 'Liquefied Gases in Bulk (CoF/GC Code) ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01112', 'Liquefied Gases in Bulk (ICoF/IGC Co de) ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01113', 'Minimum Safe Manning Document ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01114', 'Dangerous Chemicals in Bulk (CoF/BCH Code) ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01115', 'Dangerous Chemicals in Bulk (I CoF/IBC Code) ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01116', 'Operational Limitations for Passenger ships ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01117', 'International Oil Pollution Prevention (IOPP) ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01118', 'Pol lution Prevention by Noxious Liquid Sub in Bulk ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01119', 'International Sewage Pollution Prevention Cert. ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01120', 'Statement of Compl iance CAS ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01121', 'Interim Statement of Compliance CAS ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01122', 'International ship security certificate ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01123', 'Continuous synopsis r ecord ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01124', 'International Air Pollution Cert. ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01125', 'Engine International Air Pollution Prev. Cert. ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01126', 'Document of Complian ce Dangerous Goods ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01127', 'Special Purpose Ship Safety ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01128', 'High Speed Cr aft Safety and Permit to Operate ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01129', 'Mobile Offshore Drilling Unit Safety ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01130', 'INF certificate of fitness ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01131', 'Internatio nal Anti-fouling-System Certificate  ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01132', 'Tonnage certificate ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01133', 'Civil Liability for Oil Pollution Damage Certificate ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01135', 'Documents for carriage of dangerous goods ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01138', 'International Energy Efficiency Certificate ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01139', 'Maritime Labour Certifica te ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01140', 'Declaration of Maritime Labour Compliance (part I and II) ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01199', 'Other (certificates) ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01201', 'Certificates for master and officers ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01202', 'Certificate for rating for watchkeeping ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01203', 'Certif icates for radio personnel ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01204', 'Certificate for personnel on tankers ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01205', 'Certificate for personnel on fast rescue boats ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01206', 'Certificate for advanced fire-fighting ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01209', 'Manning specified by the minimum safe manning doc ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01210', 'Certificate for medic al first aid ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01211', 'Cert for personnel on survival craft & rescue boat ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01212', 'Certificate for medical care ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01213', 'Evidence of Ba sic Training ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01214', 'Endorsement by flag State ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01215', 'Application for Endorsement by flag State ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01217', 'Ship Security Officer Cert ificate ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01218', 'Medical certificate ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01219', 'Training and qualification MLC - Personal safety training ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01220', 'Seafarers'' employment  agreement (SEA) ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01221', 'Record of employment ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01222', 'Doc evidence for personnel on passenger ships', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01302', 'SAR Co-operation plan for pass. ships trade on fixed route ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01303', 'Unattended Machinery Spaces (UMS) Evidence ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01304', 'Declarat ion of AFS compliance ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01305', 'Log-books/compulsory entries ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01306', 'Schedules for watchkeeping personnel ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01307', 'Tables of working h ours ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01308', 'Records of rest ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01309', 'Fire control plan - all ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01310', 'Signs, indications ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01311', 'Survey report file ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01312', 'Thickness  measurement report ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01313', 'Booklet for bulk cargo loading/unloading/stowage ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01314', 'SOPEP ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01315', 'Oil record book ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01316', 'Cargo info rmation ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01317', 'Cargo record book ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01318', 'P&A manual ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01319', 'Shipboard mar.poll.emergency plan for NLS ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01320', 'Garbage record book ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01321', 'Endorsement of cargo booklet ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01322', 'Conformance Test Report ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01323', 'Fire safety operational booklet   ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01324', 'Material Safet y Data Sheets (MSDS) ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01325', 'ACM statement of compliance (including exemption) ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01326', 'Stability Information Booklet ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01327', 'Energy  Efficiency Design Index File ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01328', 'Ship Energy Efficiency Management plan ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01329', 'Report of inspection on MLC, 2006', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01330', 'Proc edure for complaint under MLC, 2006', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01331', 'Collective bargaining agreement ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01332', 'AIS test report ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01333', 'Ship specific plans for the recovery of persons from the water ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '01334', 'STS Operation Plan and Record s of STS Operations ', 1);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '02101', 'Closing devices/watertight doors ', 2);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '02102', 'Damage control plan ', 2);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '02103', 'Stabil ity/strength/loading information and instruments ', 2);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '02104', 'Information on the A/A-max Ratio (Roro/pass.only) ', 2);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '02105', 'Steering gear', 2);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '02106', 'Hull damage impairing seaworthiness ', 2);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '02107', 'Ballast, fuel and other tanks ', 2);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '02108', 'Electrical installations in general ', 2);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '02109', ' Permanent means of access ', 2);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '02110', 'Beams, frames, floors-op.damage ', 2);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '02111', 'Beams, frames, floors-corrosion ', 2);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '02112', 'Hull - corrosion  ', 2);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '02113', 'Hull - cracking ', 2);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '02114', 'Bulkhead -corrosion ', 2);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '02115', 'Bulkheads - operational damage ', 2);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '02116', 'Bulkheads - cracking ', 2);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '02117', 'Decks  - corrosion ', 2);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '02118', 'Decks - cracking ', 2);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '02119', 'Enhanced survey programme (ESP) ', 2);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '02120', 'Marking of IMO number ', 2);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '02121', 'Cargo area segre gation ', 2);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '02122', 'Openings to cargo area, doors, ... scuttles ', 2);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '02123', 'Wheelhouse -door -window ', 2);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '02124', 'Cargo pumproom ', 2);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '02125', 'Spaces in  cargo areas ', 2);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '02126', 'Cargo tank vent system ', 2);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '02127', 'Safe access to tanker bows', 2);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '02129', 'Bulkhead strength ', 2);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '02130', 'Triangle mark ', 2);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '02132', 'Water level detectors on single hold cargo ships ', 2);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '02133', 'Asbestos containin g materials ', 2);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '02134', 'Loading/Ballast condition ', 2);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '02199', 'Other (Structure condition) ', 2);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '03101', 'Overl oading ', 3);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '03102', 'Freeboard marks ', 3);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '03103', 'Railing, gangway, walkway and means for safe passage ', 3);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '03104', 'Cargo & other hatchways ', 3);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '03105', ' Covers (hatchway-, portable-, tarpaulins, etc.) ', 3);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '03106', 'Windows, sidescuttles and deadlights ', 3);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '03107', 'Doors', 3);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '03108', 'Ventilators, air  pipes, casings ', 3);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '03109', 'Machinery space openings ', 3);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '03110', 'Manholes/flush scuttles ', 3);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '03111', 'Cargo ports and other similar openings ', 3);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '03112', 'Scuppers, inlets and discharges ', 3);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '03113', 'Bulwarks and freeing ports ', 3);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '03114', 'Stowage incl.uprights, lashing,etc. (timber) ', 3);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '03199', ' Other (load lines) ', 3);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '04101', 'Public address system ', 4);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '04102', 'Emergency fire pump and its pipes ', 4);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '04103', 'Emergenc y, lighting, batteries and switches ', 4);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '04104', 'Low level lighting in corridors ', 4);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '04105', 'Location of emergency installations ', 4);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '04106', 'Eme rgency steering position com./ compass reading ', 4);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '04107', 'Emergency towing arrangements and procedures ', 4);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '04108', 'Muster list', 4);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '04109', 'Fire drills ', 4);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '04110', 'Abandon ship drills ', 4);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '04111', 'Damage control plan ', 4);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '04112', 'Shipbo ard Marine Pollution emergency operations ', 4);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '04113', 'Water level indicator ', 4);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '04114', 'Emergency source of power - Emergency generator ', 4);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '04115', 'Safe areas ', 4);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '04116', 'Means of communication between safety centre and other control stations ', 4);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '04117', 'Functionality of Safety Sy stems ', 4);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '04118', 'Enclosed space entry and rescue drills ', 4);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '05101', 'Distress messages: obligations and procedu res ', 5);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '05102', 'Functional requirements ', 5);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '05103', 'Main installation ', 5);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '05104', 'MF Radio installation ', 5);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '05105', 'MF/HF Radio installation ', 5);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '05106', ' INMARSAT ship earth station ', 5);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '05107', 'Maintenance/duplication of equipment ', 5);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '05108', 'Performance standards for radio equipment ', 5);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '05109', ' VHF radio installation ', 5);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '05110', 'Facilities for reception of marine safety inform. ', 5);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '05111', 'Satellite EPIRB 406MHz/1.6GHz ', 5);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '05112', 'VHF  EPIRB ', 5);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '05113', 'SART/AIS-SART ', 5);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '05114', 'Reserve source of energy ', 5);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '05115', 'Radio log (diary) ', 5);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '05116', 'Operation/maintenance ', 5);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '05118', 'Operatio n of GMDSS equipment ', 5);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '05199', 'Other (radiocommunication) ', 5);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '06101', 'Cargo Securing Manual', 6);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '06102', 'Grain', 6);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '06103', 'Other cargo/timber/deck/construction ', 6);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '06104', 'Lashing materi al ', 6);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '06106', 'Cargo transfer - Tankers ', 6);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '06107', 'Cargo operation ', 6);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '06108', 'Cargo density declaration ', 6);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '06109', 'Loading instrument ', 6);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '06199', 'Othe r (cargo) ', 6);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '07101', 'Fire prevention structural integrity ', 7);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '07102', 'Inert gas system ', 7);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '07103', 'Division - decks,bulkhead s and penetrations ', 7);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '07104', 'Main Vertical zone ', 7);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '07105', 'Fire doors/openings in fire-resisting divisions ', 7);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '07106', 'Fire detection and al arm system ', 7);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '07107', 'Fire patrol ', 7);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '07108', 'Ready availability of fire fighting equipment ', 7);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '07109', 'Fixed fire extinguishing installation  ', 7);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '07110', 'Fire fighting equipment and appliances ', 7);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '07111', 'Personal equipment for fire safety ', 7);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '07112', 'Emergency Escape Breathing Device  and disposition ', 7);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '07113', 'Fire pumps and its pipes ', 7);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '07114', 'Remote Means of control (opening,pumps,ventilation,etc.) Machinery space s', 7);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '07115', 'Fire-dampers', 7);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '07116', 'Ventilation', 7);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '07117', 'Jacketed high pressure lines and oil leakage alarm ', 7);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '07118', 'International shore-conne ction ', 7);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '07120', 'Means of escape ', 7);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '07121', 'Crew alarm ', 7);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '07122', 'Fire control plan ', 7);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '07123', 'Operation of Fire protection systems ', 7);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '07124', 'Maint enance of Fire protection systems', 7);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '07125', 'Evaluation of crew performance (fir e drills) ', 7);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '07126', 'Oil accumulation in engine room ', 7);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '07199', 'Other (fire safety) ', 7);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '08101', 'General alarm ', 8);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '08102', 'Emergency s ignal ', 8);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '08103', 'Fire alarm ', 8);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '08104', 'Steering gear alarm ', 8);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '08105', 'Engineers'' alarm ', 8);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '08106', 'Inert gas alarm ', 8);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '08107', 'Machinery controls alar m ', 8);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '08108', 'UMS - alarms ', 8);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '08109', 'Boiler alarm ', 8);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '08110', 'Closing water-tight doors alarm ', 8);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '08199', 'Other (alarms) ', 8);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09101', 'Minimum age ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09102', 'Dirty, parasites ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09103', 'Ventilati on (Accommodation)  ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09103', 'Ventilation (Accommodation)  ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09104', 'Heating', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09105', 'Noise', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09106', 'Sanitary Facilities ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09107', 'Drainage', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09108', 'Lighting (Accommodation) ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09108', 'Lighting (Accommodation) ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09109', 'Pipes, wires (insulation) ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09110', 'Electrical devices ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09111', 'Si ckbay', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09112', 'Medical Equipment', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09113', 'Access/structure ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09114', 'Sleeping room ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09115', 'No direct openings into sleeping rooms cargo/mach. ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09116', 'Furnishings', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09117', 'Berth dimensions, etc. ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09118', 'Clear head ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09119', ' Messroom (location) ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09120', 'Clothes locker ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09121', 'Laundry', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09122', 'Record of inspection (Accommodation) ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09124', 'Galley, handlingroom  (maintenance) ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09127', 'Cleanliness', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09128', 'Provisions quantity ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09129', 'Provisions quality ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09130', 'Water, pipes, tanks ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09131', 'Cold roo m ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09132', 'Cold room temperature ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09133', 'Cold room cleanliness ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09134', 'Food personal hygiene ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09135', 'Food temperature ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09136', 'Food seg regation ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09137', 'Record of inspection ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09198', 'Other (crew and accommodation) ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09199', 'Other (food) ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09201', 'Ventilation (Working spaces) ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09202', 'Heating', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09203', 'Lighting (Working spaces) ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09204', 'Safe means o f access ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09205', 'Safe means of access Shore - Ship ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09206', 'Safe means of access Deck - hold/tank, etc. ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09207', 'Obstruction/slipping , etc.', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09208', 'Protection machinery ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09209', 'Electrical', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09210', 'Machinery ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09211', ' Steam pipes and pressure pipes ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09212', 'Danger areas ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09213', 'Gas instruments ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09214', 'Emergency cleaning devices ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09216', 'Personal equ ipment ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09217', 'Warning notices ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09218', 'Protection machines/parts ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09219', 'Pipes, wires (insulation) ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09220', 'Structural features (ship ) ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09221', 'Entry dangerous spaces ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09223', 'Gangway, accommodation-ladder ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09224', 'Stowage of cargo ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09225', 'Loading and unloading equipm ent ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09226', 'Holds and tanks safety ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09227', 'Ropes and wires ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09228', 'Anchoring devices ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09229', 'Winches & capstans ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09230', 'Adequate ligh ting - mooring arrangements ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09232', 'Cleanliness of engine room ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09233', 'Guards - fencing around dangerous machinery parts ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09234', 'Ni ght Working for seafarer under the age of 18', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09235', 'Fitness for duty - work and rest hours ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09236', 'Legal documentation on work an d rest hours ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09237', 'Fitness for duty - intoxication ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09297', 'Other (working space ILO) ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09298', 'Other (accident prevention) ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '09299', 'O ther (mooring) ', 9);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '10101', 'Pilot ladders and hoist/pilot transfer arrangements', 10);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '10102', 'Type approval equipment ', 10);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '10103', 'Radar', 10);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '10104', 'Gyro compass ', 10);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '10105', 'Magnetic compass ', 10);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '10106', 'Compass  correction log ', 10);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '10107', 'Automatic radar plotting aid (ARPA) ', 10);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '10109', 'Lights, shapes, sound-signals ', 10);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '10110', 'Signalling lamp ', 10);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '10111', 'Ch arts', 10);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '10112', 'Electronic charts (ECDIS)  ', 10);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '10113', 'Automatic Identification System (AIS) ', 10);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '10114', 'Voyage data recorder (VDR)/Simplified  Voyage data recorder(S-VDR) ', 10);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '10115', 'GNSS receiver/terrestrial radio navigation system ', 10);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '10116', 'Nautical publications ', 10);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '10117', 'Echo so under ', 10);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '10118', 'Speed and distance indicator ', 10);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '10119', 'Rudder angle indicator ', 10);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '10120', 'Revolution counter ', 10);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '10121', 'Variable pitch indicato r ', 10);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '10122', 'Rate-of-turn indicator ', 10);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '10123', 'International code of signals-SOLAS ', 10);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '10124', 'Life-saving signals ', 10);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '10125', 'Use of the automati c pilot ', 10);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '10126', 'Record of drills and steering gear tests ', 10);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '10127', 'Voyage or passage plan ', 10);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '10128', 'Navigation bridge visibility ', 10);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '10129', ' Navigation records ', 10);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '10132', 'Communication-SOLAS chap. 5', 10);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '10133', 'Bridge operation ', 10);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '10134', 'HSC operation ', 10);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '10135', 'Monitoring of voyage  or passage plan ', 10);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '10136', 'Establishment of working language onboard ', 10);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '10137', 'Long-range identification and tracking system (LRIT)', 10);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '10138', 'Bridge Navigation Watch Alarm System (BNWAS) ', 10);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '10199', 'Other (navigation)  ', 10);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '11101', 'Lifeboats', 11);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '11102', 'Lifeboat inventory ', 11);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '11103', 'Stowage and provision of Lifeboats ', 11);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '11104', 'Rescue  boats ', 11);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '11105', 'Rescue boat inventory ', 11);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '11106', 'Fast Rescue Boats ', 11);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '11107', 'Stowage of rescue boats ', 11);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '11108', 'Inflatable liferafts ', 11);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '11109', 'R igid liferafts ', 11);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '11110', 'Stowage and provision of liferafts ', 11);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '11111', 'Marine Evacuation System ', 11);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '11112', 'Launching  arrangements for surv ival craft ', 11);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '11113', 'Launching  arrangements for rescue boats ', 11);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '11114', 'Helicopter landing and pick-up area ', 11);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '11115', 'Means of rescue ', 11);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '11116', 'Distress flares ', 11);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '11117', 'Lifebuoys incl. provision and disposition ', 11);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '11118', 'Lifejackets incl.provision and disposition ', 11);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '11119', 'Im mersion suits ', 11);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '11120', 'Anti-exposure suits ', 11);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '11121', 'Thermal Protective Aids ', 11);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '11122', 'Radio life-saving appliances ', 11);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '11123', 'Emergency equ ipment for 2-way comm. ', 11);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '11124', 'Embarkation arrangement survival craft ', 11);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '11125', 'Embarkation arrangements rescue boats ', 11);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '11126', 'Means o f recovery of life saving appliances ', 11);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '11127', 'Buoyant apparatus ', 11);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '11128', 'Line-throwing appliance ', 11);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '11129', 'Operational readiness of lif esaving appliances', 11);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '11130', 'Evaluation, testing and approval ', 11);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '11131', 'On board  training and instructions ', 11);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '11132', 'Maintenance and inspections ', 11);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '11134', 'Operation of Life Saving Appliances ', 11);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '11135', 'Maintenance of L ife Saving Appliances ', 11);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '11199', 'Other (life saving) ', 11);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '12101', 'Stowage/segregation/packaging dangerous goods ', 12);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '12104', 'Dangerous Goods Code ', 12);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '12105', 'Temperature control ', 12);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '12106', 'Instrumentation', 12);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '12107', 'Fire protection cargo deck area ', 12);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '12108', 'Personal  protection ', 12);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '12109', 'Special requirement ', 12);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '12110', 'Tank entry ', 12);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '12112', 'Dangerous goods / harmful substances in pack. Form ', 12);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '12199', 'Other  (tankers) ', 12);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '13101', 'Propulsion main engine ', 13);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '13102', 'Auxiliary engine ', 13);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '13103', 'Gauges,thermome ters, etc ', 13);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '13104', 'Bilge pumping arrangements ', 13);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '13105', 'UMS - Ship ', 13);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '13106', 'Insulation wetted through (oil) ', 13);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '13108', 'Operation of machine ry ', 13);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '13199', 'Other (machinery) ', 13);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14101', 'Control of discharge  ', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14102', 'Retention of oil on board', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14103', 'Segregation of oil and water ball ast ', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14104', 'Oil filtering equipment ', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14105', 'Pumping, piping and discharge arrangements ', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14106', 'Pump room bottom Protection ', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14107', 'O il disch. Monitoring and control system ', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14108', '15 PPM Alarm arrangmts.', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14109', 'Oil/water interface detector ', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14110', 'Standard disch . conn. ', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14111', 'SBT, CBT, COW ', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14112', 'Cow operations and equipment manual ', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14113', 'Double hull construction ', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14114', 'Hydrostatically b alanced loading ', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14115', 'Condition assessment scheme ', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14116', 'Pollution report-MARPOL Annex I ', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14117', 'Ship type designation ', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14119', 'Oi l and oily mixtures from machinery spaces ', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14120', 'Load, unload & clean proc. for cargo sp.(tankers) ', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14121', 'Suspected of discharge  violation ', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14122', 'Oil fuel tank protection ', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14123', 'Accidental oil outflow performance ', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14199', 'Other (MARPOL Annex I) ', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14201', 'Efficient stripping ', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14202', 'Residue disch.systems ', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14203', 'Tank washing equipm. ', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14204', 'Pro hibited discharge of NLS slops ', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14205', 'Cargo heating systems - cat Y substances ', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14206', 'Vent. Procedures/equipment ', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14207', 'Pollutio n report-MARPOL Annex II ', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14208', 'Ship type designation ', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14299', 'Other (MARPOL Annex II)', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14301', 'Packaging ', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14302', 'Marking and labelling ', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14303', 'Documentation (MA RPOL Annex III) ', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14304', 'Stowage', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14399', 'Other (MARPOL Annex III) ', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14402', 'Sewage treat ment plant ', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14403', 'Sewage comminuting and disinfecting system ', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14404', 'Sewage discharge connection ', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14499', 'Other (MARPOL Annex IV) ', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14501', 'Garbage', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14502', 'Placards', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14503', 'Garbage management plan ', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14599', 'Other (MARPOL An nex V9', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14601', 'Technical files and if applicable, monitoring manual ', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14602', 'Record  book of engine parameters ', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14603', 'Approval for exhaust gas cleaning system  ', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14604', 'Bunker delivery notes', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14605', 'Type approval cert ificate of incinerator  ', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14606', 'Diesel engine relating to air pollution control ', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14607', 'Quality of fuel oil  ', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14608', 'Incinerator in cl.operations and operating manual  ', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14609', 'Volatile organic compounds in tankers  ', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14610', 'Operational procedures for engines or e quipment  ', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14611', 'Ozone-depleting substances  ', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14613', 'Approved method', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14614', ' Sulphur oxides ', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14699', 'Other (MARPOL Annex VI) ', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14701', 'AFS supporting documentation ', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14702', 'Logbook entries referring AFS ', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14703', 'Paint condition ', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '14799', 'Other (AFS) ', 14);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '15101', 'Safety and environment policy ', 15);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '15102', 'Company responsibility and authority ', 15);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '15103', 'Designated person(s) ', 15);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '15104', 'Masters responsibility and authority ', 15);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '15105', 'Resource s and personnel ', 15);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '15106', 'Shipboard operations ', 15);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '15107', 'Emergency preparedness ', 15);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '15108', 'Reports of non-conf., accidents & hazardous occ ur. ', 15);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '15109', 'Maintenance of the ship and equipment ', 15);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '15110', 'Documentation-ISM', 15);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '15111', 'Company verification, review and evaluation ', 15);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '15112', 'Certification, verification and control ', 15);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '15199', 'Other (ISM) ', 15);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18101', 'Minimum age ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18102', 'Night Working ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18103', 'Medical fitness ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18104', 'Recruitment and placement service ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18199', 'Other (Minimum requirements) ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18201', 'Fitness for duty - work and rest hours ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18202', 'Legal documentation on work and rest hours ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18203', 'Wages', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18204', 'C alculation and payment of wages ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18205', 'Measures to ensure transmission to seafarer''s family ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18299', 'Other (Conditions of employme nt) ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18301', 'Noise, vibration and other ambi ent factors ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18302', 'Sanitary Facilities ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18303', 'Drainage', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18304', 'Lighting (Accommodation) ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18305', 'Hospital accommodation (Sickbay)  ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18306', 'Sleeping room, additional spaces ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18307', 'No direct openings into sleeping rooms cargo/mach. ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18308', 'Furnishings', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18309', 'Berth  dimensions, etc. ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18310', 'Minimum headroom ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18311', 'Messroom and recreational facilities ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18312', 'Galley, handling room (maintenance)  ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18313', 'Cleanliness', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18314', 'Provisions quantity ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18315', 'Provisions quality and nutritional value ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18316', 'Water, pipes, tanks ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18317', 'F ood personal hygiene ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18318', 'Food temperature ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18319', 'Food segregation ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18320', 'Record of inspection (food and catering) ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18321', 'Heat ing, air conditioning and ventilation ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18322', 'Insulation', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18323', 'Office', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18324', 'Cold room, cold room cleanliness, cold room temperatu re ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18325', 'Training and qualification of ship''s cook', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18326', 'Laundry, Adequa te Locker ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18327', 'Ventilation (Working spaces) ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18328', 'Record of inspection ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18399', 'Other (Accommodation, recreational facilities.. .) ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18401', 'Medical Equipment, medical chest, medical  guide  ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18402', 'Access to on shore medical doctor or dentist ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18403', 'Standard medical report form ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18404', 'Medical doctor or person  in charge of medical care ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18405', 'Medical advice by radio or satellite ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18406', 'Medical care onboard or ashore free of charge ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18407', 'Lighting (Working spaces) ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18408', 'Electrical', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18409', 'Dangerous areas ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18410', 'Gas instruments ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18411', 'Emergency cleaning devices ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18412', 'Personal equipment ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18413', 'Warning notices ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18414', 'Protection machines/parts ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18415', 'Entry dangerous spaces ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18416', 'Ropes and wi res ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18417', 'Anchoring devices ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18418', 'Winches & capstans ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18419', 'Adequate lighting - mooring arrangements ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18420', 'Cleanliness of eng ine room ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18421', 'Guards - fencing around dangerous machinery parts ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18422', 'Asbestos fibres ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18423', 'Preventative information ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18424', ' Steam pipes, pressure pipes, wires (insulation) ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18425', 'Access / structural features (ship) ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18426', 'Exposure to harmful levels of  ambiant factors ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18427', 'Ship''s occupational safety and health policies and programmes', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18428', 'On board programme for the prevention of occupational injuries and diseases', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18429', 'Procedure for inspection, re porting and correcting unsafe conditions and for investigating and reporting on-board occupational accidents ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18430', 'Ship''s safet y committee ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18431', 'Investigation after accident ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18432', 'Risk evaluation, training and instruction to seafarers ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '18499', 'Other (Heal th protection, medical care...) ', 16);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '99101', 'Other safety in general ', 17);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '99102', 'Other (SOLAS operational) ', 17);
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '99103', 'Other (MARPO L operational) ', 17);
			
INSERT INTO ms_deficiency_code(deficiency_code_name, defective_item, deficiency_category_id) VALUES ( '00000', 'Other', 18);
