//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeficiencyControl.WcfServiceDeficiency {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfServiceDeficiency.IServiceDeficiency")]
    public interface IServiceDeficiency {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/GetServerDate", ReplyAction="http://tempuri.org/IServiceDeficiency/GetServerDateResponse")]
        System.DateTime GetServerDate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/Login", ReplyAction="http://tempuri.org/IServiceDeficiency/LoginResponse")]
        DcCommon.DB.UserData Login(string loginid, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/LogoutUser", ReplyAction="http://tempuri.org/IServiceDeficiency/LogoutUserResponse")]
        bool LogoutUser(CIsl.DB.WingDAC.MsUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/DcAttachment_DownloadAttachment", ReplyAction="http://tempuri.org/IServiceDeficiency/DcAttachment_DownloadAttachmentResponse")]
        DcCommon.DB.DAC.DcAttachment DcAttachment_DownloadAttachment(int attachment_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/PSCInspectionData_GetDataByCommentItemID", ReplyAction="http://tempuri.org/IServiceDeficiency/PSCInspectionData_GetDataByCommentItemIDRes" +
            "ponse")]
        DcCommon.DB.PSCInspectionData PSCInspectionData_GetDataByCommentItemID(int comment_item_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/PSCInspectionData_InsertList", ReplyAction="http://tempuri.org/IServiceDeficiency/PSCInspectionData_InsertListResponse")]
        bool PSCInspectionData_InsertList(DcCommon.DB.CommentData comhead, System.Collections.Generic.List<DcCommon.DB.PSCInspectionData> datalist, CIsl.DB.WingDAC.MsUser requser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/PSCInspectionData_GetDataListBySearchData", ReplyAction="http://tempuri.org/IServiceDeficiency/PSCInspectionData_GetDataListBySearchDataRe" +
            "sponse")]
        System.Collections.Generic.List<DcCommon.DB.PSCInspectionData> PSCInspectionData_GetDataListBySearchData(DcCommon.DB.DAC.Search.PscInspectionSearchData sdata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/PSCInspectionData_UpdateWithSister", ReplyAction="http://tempuri.org/IServiceDeficiency/PSCInspectionData_UpdateWithSisterResponse")]
        bool PSCInspectionData_UpdateWithSister(DcCommon.DB.CommentData comhead, DcCommon.DB.PSCInspectionData pscdata, CIsl.DB.WingDAC.MsUser requser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/PSCInspectionData_Delete", ReplyAction="http://tempuri.org/IServiceDeficiency/PSCInspectionData_DeleteResponse")]
        bool PSCInspectionData_Delete(int comment_item_id, CIsl.DB.WingDAC.MsUser requser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/DcCiPscInspection_UpdateStatus", ReplyAction="http://tempuri.org/IServiceDeficiency/DcCiPscInspection_UpdateStatusResponse")]
        bool DcCiPscInspection_UpdateStatus(System.Collections.Generic.List<DcCommon.DB.DAC.DcCiPscInspection> psclist, CIsl.DB.WingDAC.MsUser requser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/DcAttachment_GetARecrodsAllByCommentItemID", ReplyAction="http://tempuri.org/IServiceDeficiency/DcAttachment_GetARecrodsAllByCommentItemIDR" +
            "esponse")]
        System.Collections.Generic.List<DcCommon.DB.DAC.DcAttachment> DcAttachment_GetARecrodsAllByCommentItemID(int comment_item_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/DcAccident_GetRecordsBySearchData", ReplyAction="http://tempuri.org/IServiceDeficiency/DcAccident_GetRecordsBySearchDataResponse")]
        System.Collections.Generic.List<DcCommon.DB.DAC.DcAccident> DcAccident_GetRecordsBySearchData(DcCommon.DB.DAC.Search.AccidentSearchData sdata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/AccidentData_GetDataByAccidentID", ReplyAction="http://tempuri.org/IServiceDeficiency/AccidentData_GetDataByAccidentIDResponse")]
        DcCommon.DB.AccidentData AccidentData_GetDataByAccidentID(int accident_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/AccidentData_InsertData", ReplyAction="http://tempuri.org/IServiceDeficiency/AccidentData_InsertDataResponse")]
        int AccidentData_InsertData(DcCommon.DB.AccidentData data, CIsl.DB.WingDAC.MsUser requser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/AccidentData_UpdateData", ReplyAction="http://tempuri.org/IServiceDeficiency/AccidentData_UpdateDataResponse")]
        bool AccidentData_UpdateData(DcCommon.DB.AccidentData data, CIsl.DB.WingDAC.MsUser requser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/AccidentData_DeleteData", ReplyAction="http://tempuri.org/IServiceDeficiency/AccidentData_DeleteDataResponse")]
        bool AccidentData_DeleteData(int accident_id, CIsl.DB.WingDAC.MsUser requser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/DcAccident_UpdateStatus", ReplyAction="http://tempuri.org/IServiceDeficiency/DcAccident_UpdateStatusResponse")]
        bool DcAccident_UpdateStatus(System.Collections.Generic.List<DcCommon.DB.DAC.DcAccident> aclist, CIsl.DB.WingDAC.MsUser requser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/CreateAccidentReportNo", ReplyAction="http://tempuri.org/IServiceDeficiency/CreateAccidentReportNoResponse")]
        string CreateAccidentReportNo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/DcAttachment_GetARecrodsAllByAccidentID", ReplyAction="http://tempuri.org/IServiceDeficiency/DcAttachment_GetARecrodsAllByAccidentIDResp" +
            "onse")]
        System.Collections.Generic.List<DcCommon.DB.DAC.DcAttachment> DcAttachment_GetARecrodsAllByAccidentID(int accident_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/MoiData_GetDataListBySearchData", ReplyAction="http://tempuri.org/IServiceDeficiency/MoiData_GetDataListBySearchDataResponse")]
        System.Collections.Generic.List<DcCommon.DB.MoiData> MoiData_GetDataListBySearchData(DcCommon.DB.DAC.Search.MoiSearchData sdata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/Moi_Insert", ReplyAction="http://tempuri.org/IServiceDeficiency/Moi_InsertResponse")]
        int Moi_Insert(DcCommon.DB.MoiHeaderData hdata, System.Collections.Generic.List<DcCommon.DB.MoiObservationData> obslist, CIsl.DB.WingDAC.MsUser requser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/MoiData_GetDataByMoiObservationID", ReplyAction="http://tempuri.org/IServiceDeficiency/MoiData_GetDataByMoiObservationIDResponse")]
        DcCommon.DB.MoiData MoiData_GetDataByMoiObservationID(int moi_observation_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/DcAttachment_GetARecrodsAllByMoi", ReplyAction="http://tempuri.org/IServiceDeficiency/DcAttachment_GetARecrodsAllByMoiResponse")]
        System.Collections.Generic.List<DcCommon.DB.DAC.DcAttachment> DcAttachment_GetARecrodsAllByMoi(int moi_observation_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/MoiData_UpdatetData", ReplyAction="http://tempuri.org/IServiceDeficiency/MoiData_UpdatetDataResponse")]
        bool MoiData_UpdatetData(DcCommon.DB.MoiData data, CIsl.DB.WingDAC.MsUser requser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/MoiData_DeleteData", ReplyAction="http://tempuri.org/IServiceDeficiency/MoiData_DeleteDataResponse")]
        bool MoiData_DeleteData(int moi_observation_id, CIsl.DB.WingDAC.MsUser requser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/DcMoiObservation_UpdateStatus", ReplyAction="http://tempuri.org/IServiceDeficiency/DcMoiObservation_UpdateStatusResponse")]
        bool DcMoiObservation_UpdateStatus(System.Collections.Generic.List<DcCommon.DB.DAC.DcMoiObservation> obslist, CIsl.DB.WingDAC.MsUser requser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/GetAccidentExcelTemplate", ReplyAction="http://tempuri.org/IServiceDeficiency/GetAccidentExcelTemplateResponse")]
        byte[] GetAccidentExcelTemplate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/GetAccidentOutputData", ReplyAction="http://tempuri.org/IServiceDeficiency/GetAccidentOutputDataResponse")]
        System.Collections.Generic.List<DcCommon.Output.AccidentOutputData> GetAccidentOutputData(DcCommon.Output.AccidentOutputParameter param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/DcSchedulePlan_GetRecordsBySearchData", ReplyAction="http://tempuri.org/IServiceDeficiency/DcSchedulePlan_GetRecordsBySearchDataRespon" +
            "se")]
        System.Collections.Generic.List<DcCommon.DB.DAC.DcSchedulePlan> DcSchedulePlan_GetRecordsBySearchData(DcCommon.DB.DAC.Search.SchedulePlanSearchData sdata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/DcSchedulePlan_InsertUpdateList", ReplyAction="http://tempuri.org/IServiceDeficiency/DcSchedulePlan_InsertUpdateListResponse")]
        bool DcSchedulePlan_InsertUpdateList(System.Collections.Generic.List<DcCommon.DB.DAC.DcSchedulePlan> datalist, CIsl.DB.WingDAC.MsUser requser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/DcScheduleCompany_GetRecordsBySearchData", ReplyAction="http://tempuri.org/IServiceDeficiency/DcScheduleCompany_GetRecordsBySearchDataRes" +
            "ponse")]
        System.Collections.Generic.List<DcCommon.DB.DAC.DcScheduleCompany> DcScheduleCompany_GetRecordsBySearchData(DcCommon.DB.DAC.Search.ScheduleCompanySearchData sdata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/DcScheduleOther_GetRecordsBySearchData", ReplyAction="http://tempuri.org/IServiceDeficiency/DcScheduleOther_GetRecordsBySearchDataRespo" +
            "nse")]
        System.Collections.Generic.List<DcCommon.DB.DAC.DcScheduleOther> DcScheduleOther_GetRecordsBySearchData(DcCommon.DB.DAC.Search.ScheduleOtherSearchData sdata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/DcScheduleCompany_InsertUpdateList", ReplyAction="http://tempuri.org/IServiceDeficiency/DcScheduleCompany_InsertUpdateListResponse")]
        bool DcScheduleCompany_InsertUpdateList(System.Collections.Generic.List<DcCommon.DB.DAC.DcScheduleCompany> datalist, CIsl.DB.WingDAC.MsUser requser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/DcScheduleOther_InsertUpdateList", ReplyAction="http://tempuri.org/IServiceDeficiency/DcScheduleOther_InsertUpdateListResponse")]
        bool DcScheduleOther_InsertUpdateList(System.Collections.Generic.List<DcCommon.DB.DAC.DcScheduleOther> datalist, CIsl.DB.WingDAC.MsUser requser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/GetPSCOutputData", ReplyAction="http://tempuri.org/IServiceDeficiency/GetPSCOutputDataResponse")]
        DcCommon.Output.PscOutputData GetPSCOutputData(DcCommon.Output.PscOutputParameter param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/GetPSCExcelTemplate", ReplyAction="http://tempuri.org/IServiceDeficiency/GetPSCExcelTemplateResponse")]
        byte[] GetPSCExcelTemplate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/GetMoiExcelCategoryTemplate", ReplyAction="http://tempuri.org/IServiceDeficiency/GetMoiExcelCategoryTemplateResponse")]
        byte[] GetMoiExcelCategoryTemplate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/GetMoiExcelListTemplate", ReplyAction="http://tempuri.org/IServiceDeficiency/GetMoiExcelListTemplateResponse")]
        byte[] GetMoiExcelListTemplate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/GetMoiReportCommentListTemplate", ReplyAction="http://tempuri.org/IServiceDeficiency/GetMoiReportCommentListTemplateResponse")]
        byte[] GetMoiReportCommentListTemplate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/GetMoiReportObservationTemplate", ReplyAction="http://tempuri.org/IServiceDeficiency/GetMoiReportObservationTemplateResponse")]
        byte[] GetMoiReportObservationTemplate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/GetMoiExcelDataCategory", ReplyAction="http://tempuri.org/IServiceDeficiency/GetMoiExcelDataCategoryResponse")]
        DcCommon.Output.MoiExcelOutputDataCategory GetMoiExcelDataCategory(DcCommon.Output.MoiExcelOutputParameter param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/GetMoiExcelDataCategory2", ReplyAction="http://tempuri.org/IServiceDeficiency/GetMoiExcelDataCategory2Response")]
        DcCommon.Output.MoiExcelOutputDataCategory GetMoiExcelDataCategory2(DcCommon.Output.MoiExcelOutputParameter param, CIsl.DB.WingDAC.MsViqVersion version);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/GetScheduleListTemplateFile", ReplyAction="http://tempuri.org/IServiceDeficiency/GetScheduleListTemplateFileResponse")]
        byte[] GetScheduleListTemplateFile();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/MsVessel_GetRecords", ReplyAction="http://tempuri.org/IServiceDeficiency/MsVessel_GetRecordsResponse")]
        System.Collections.Generic.List<CIsl.DB.WingDAC.MsVessel> MsVessel_GetRecords();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/MsUser_GetRecords", ReplyAction="http://tempuri.org/IServiceDeficiency/MsUser_GetRecordsResponse")]
        System.Collections.Generic.List<CIsl.DB.WingDAC.MsUser> MsUser_GetRecords();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/UserData_GetDataByMsUserID", ReplyAction="http://tempuri.org/IServiceDeficiency/UserData_GetDataByMsUserIDResponse")]
        DcCommon.DB.UserData UserData_GetDataByMsUserID(string ms_user_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/MsItemKind_GetRecords", ReplyAction="http://tempuri.org/IServiceDeficiency/MsItemKind_GetRecordsResponse")]
        System.Collections.Generic.List<CIsl.DB.WingDAC.MsItemKind> MsItemKind_GetRecords();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/MsStatus_GetRecords", ReplyAction="http://tempuri.org/IServiceDeficiency/MsStatus_GetRecordsResponse")]
        System.Collections.Generic.List<DcCommon.DB.DAC.MsStatus> MsStatus_GetRecords();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/MsAlarmColor_GetRecords", ReplyAction="http://tempuri.org/IServiceDeficiency/MsAlarmColor_GetRecordsResponse")]
        System.Collections.Generic.List<DcCommon.DB.DAC.MsAlarmColor> MsAlarmColor_GetRecords();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/MsActionCode_GetRecords", ReplyAction="http://tempuri.org/IServiceDeficiency/MsActionCode_GetRecordsResponse")]
        System.Collections.Generic.List<CIsl.DB.WingDAC.MsActionCode> MsActionCode_GetRecords();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/MsDeficiencyCode_GetRecords", ReplyAction="http://tempuri.org/IServiceDeficiency/MsDeficiencyCode_GetRecordsResponse")]
        System.Collections.Generic.List<CIsl.DB.WingDAC.MsDeficiencyCode> MsDeficiencyCode_GetRecords();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/MsVesselType_GetRecords", ReplyAction="http://tempuri.org/IServiceDeficiency/MsVesselType_GetRecordsResponse")]
        System.Collections.Generic.List<CIsl.DB.WingDAC.MsVesselType> MsVesselType_GetRecords();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/MsBasho_GetRecords", ReplyAction="http://tempuri.org/IServiceDeficiency/MsBasho_GetRecordsResponse")]
        System.Collections.Generic.List<CIsl.DB.WingDAC.MsBasho> MsBasho_GetRecords();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/MsRegional_GetRecords", ReplyAction="http://tempuri.org/IServiceDeficiency/MsRegional_GetRecordsResponse")]
        System.Collections.Generic.List<CIsl.DB.WingDAC.MsRegional> MsRegional_GetRecords();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/MsAlarmColor_InsertRecord", ReplyAction="http://tempuri.org/IServiceDeficiency/MsAlarmColor_InsertRecordResponse")]
        int MsAlarmColor_InsertRecord(DcCommon.DB.DAC.MsAlarmColor data, CIsl.DB.WingDAC.MsUser requser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/MsAlarmColor_UpdateRecord", ReplyAction="http://tempuri.org/IServiceDeficiency/MsAlarmColor_UpdateRecordResponse")]
        bool MsAlarmColor_UpdateRecord(DcCommon.DB.DAC.MsAlarmColor data, CIsl.DB.WingDAC.MsUser requser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/MsAlarmColor_DeleteRecord", ReplyAction="http://tempuri.org/IServiceDeficiency/MsAlarmColor_DeleteRecordResponse")]
        bool MsAlarmColor_DeleteRecord(DcCommon.DB.DAC.MsAlarmColor data, CIsl.DB.WingDAC.MsUser requser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/MsAccidentImportance_GetRecords", ReplyAction="http://tempuri.org/IServiceDeficiency/MsAccidentImportance_GetRecordsResponse")]
        System.Collections.Generic.List<CIsl.DB.WingDAC.MsAccidentImportance> MsAccidentImportance_GetRecords();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/MsAccidentKind_GetRecords", ReplyAction="http://tempuri.org/IServiceDeficiency/MsAccidentKind_GetRecordsResponse")]
        System.Collections.Generic.List<CIsl.DB.WingDAC.MsAccidentKind> MsAccidentKind_GetRecords();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/MsAccidentSituation_GetRecords", ReplyAction="http://tempuri.org/IServiceDeficiency/MsAccidentSituation_GetRecordsResponse")]
        System.Collections.Generic.List<CIsl.DB.WingDAC.MsAccidentSituation> MsAccidentSituation_GetRecords();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/MsAccidentStatus_GetRecords", ReplyAction="http://tempuri.org/IServiceDeficiency/MsAccidentStatus_GetRecordsResponse")]
        System.Collections.Generic.List<DcCommon.DB.DAC.MsAccidentStatus> MsAccidentStatus_GetRecords();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/MsKindOfAccident_GetRecords", ReplyAction="http://tempuri.org/IServiceDeficiency/MsKindOfAccident_GetRecordsResponse")]
        System.Collections.Generic.List<CIsl.DB.WingDAC.MsKindOfAccident> MsKindOfAccident_GetRecords();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/MsInspectionCategory_GetRecords", ReplyAction="http://tempuri.org/IServiceDeficiency/MsInspectionCategory_GetRecordsResponse")]
        System.Collections.Generic.List<CIsl.DB.WingDAC.MsInspectionCategory> MsInspectionCategory_GetRecords();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/MsViqCode_GetRecords", ReplyAction="http://tempuri.org/IServiceDeficiency/MsViqCode_GetRecordsResponse")]
        System.Collections.Generic.List<CIsl.DB.WingDAC.MsViqCode> MsViqCode_GetRecords();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/MsViqNo_GetRecords", ReplyAction="http://tempuri.org/IServiceDeficiency/MsViqNo_GetRecordsResponse")]
        System.Collections.Generic.List<CIsl.DB.WingDAC.MsViqNo> MsViqNo_GetRecords();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/MsViqNo_GetRecordsByViqCodeID", ReplyAction="http://tempuri.org/IServiceDeficiency/MsViqNo_GetRecordsByViqCodeIDResponse")]
        System.Collections.Generic.List<CIsl.DB.WingDAC.MsViqNo> MsViqNo_GetRecordsByViqCodeID(int viq_code_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/MsMoiStatus_GetRecords", ReplyAction="http://tempuri.org/IServiceDeficiency/MsMoiStatus_GetRecordsResponse")]
        System.Collections.Generic.List<DcCommon.DB.DAC.MsMoiStatus> MsMoiStatus_GetRecords();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/MsCustomer_GetRecords", ReplyAction="http://tempuri.org/IServiceDeficiency/MsCustomer_GetRecordsResponse")]
        System.Collections.Generic.List<CIsl.DB.WingDAC.MsCustomer> MsCustomer_GetRecords();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/MsCustomer_GetRecordsInspectionCompany", ReplyAction="http://tempuri.org/IServiceDeficiency/MsCustomer_GetRecordsInspectionCompanyRespo" +
            "nse")]
        System.Collections.Generic.List<CIsl.DB.WingDAC.MsCustomer> MsCustomer_GetRecordsInspectionCompany();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/MsCustomer_GetRecordsAppointedCompany", ReplyAction="http://tempuri.org/IServiceDeficiency/MsCustomer_GetRecordsAppointedCompanyRespon" +
            "se")]
        System.Collections.Generic.List<CIsl.DB.WingDAC.MsCustomer> MsCustomer_GetRecordsAppointedCompany();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/MsDeficiencyCategory_GetRecords", ReplyAction="http://tempuri.org/IServiceDeficiency/MsDeficiencyCategory_GetRecordsResponse")]
        System.Collections.Generic.List<CIsl.DB.WingDAC.MsDeficiencyCategory> MsDeficiencyCategory_GetRecords();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/MsYear_GetRecords", ReplyAction="http://tempuri.org/IServiceDeficiency/MsYear_GetRecordsResponse")]
        System.Collections.Generic.List<DcCommon.DB.DAC.MsYear> MsYear_GetRecords();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/MsScheduleCategory_GetRecords", ReplyAction="http://tempuri.org/IServiceDeficiency/MsScheduleCategory_GetRecordsResponse")]
        System.Collections.Generic.List<CIsl.DB.WingDAC.MsScheduleCategory> MsScheduleCategory_GetRecords();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/MsScheduleKind_GetRecords", ReplyAction="http://tempuri.org/IServiceDeficiency/MsScheduleKind_GetRecordsResponse")]
        System.Collections.Generic.List<CIsl.DB.WingDAC.MsScheduleKind> MsScheduleKind_GetRecords();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/MsScheduleKindDetail_GetRecords", ReplyAction="http://tempuri.org/IServiceDeficiency/MsScheduleKindDetail_GetRecordsResponse")]
        System.Collections.Generic.List<CIsl.DB.WingDAC.MsScheduleKindDetail> MsScheduleKindDetail_GetRecords();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/DeficiencyCategoryData_GetDataList", ReplyAction="http://tempuri.org/IServiceDeficiency/DeficiencyCategoryData_GetDataListResponse")]
        System.Collections.Generic.List<DcCommon.DB.DeficiencyCategoryData> DeficiencyCategoryData_GetDataList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/MsViqCodeName_GetRecords", ReplyAction="http://tempuri.org/IServiceDeficiency/MsViqCodeName_GetRecordsResponse")]
        System.Collections.Generic.List<CIsl.DB.WingDAC.MsViqCodeName> MsViqCodeName_GetRecords();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/MsViqVersion_GetRecords", ReplyAction="http://tempuri.org/IServiceDeficiency/MsViqVersion_GetRecordsResponse")]
        System.Collections.Generic.List<CIsl.DB.WingDAC.MsViqVersion> MsViqVersion_GetRecords();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/MsVesselScheduleKindDetailEnable_GetRecords" +
            "ByMsVesselID", ReplyAction="http://tempuri.org/IServiceDeficiency/MsVesselScheduleKindDetailEnable_GetRecords" +
            "ByMsVesselIDResponse")]
        System.Collections.Generic.List<CIsl.DB.WingDAC.MsVesselScheduleKindDetailEnable> MsVesselScheduleKindDetailEnable_GetRecordsByMsVesselID(decimal ms_vessel_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/MsVesselScheduleKindDetailEnable_GetRecords" +
            "", ReplyAction="http://tempuri.org/IServiceDeficiency/MsVesselScheduleKindDetailEnable_GetRecords" +
            "Response")]
        System.Collections.Generic.List<CIsl.DB.WingDAC.MsVesselScheduleKindDetailEnable> MsVesselScheduleKindDetailEnable_GetRecords();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/MsVesselCategory_GetRecords", ReplyAction="http://tempuri.org/IServiceDeficiency/MsVesselCategory_GetRecordsResponse")]
        System.Collections.Generic.List<CIsl.DB.WingDAC.MsVesselCategory> MsVesselCategory_GetRecords();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDeficiency/MsCrewMatrixType_GetRecords", ReplyAction="http://tempuri.org/IServiceDeficiency/MsCrewMatrixType_GetRecordsResponse")]
        System.Collections.Generic.List<CIsl.DB.WingDAC.MsCrewMatrixType> MsCrewMatrixType_GetRecords();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceDeficiencyChannel : DeficiencyControl.WcfServiceDeficiency.IServiceDeficiency, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceDeficiencyClient : System.ServiceModel.ClientBase<DeficiencyControl.WcfServiceDeficiency.IServiceDeficiency>, DeficiencyControl.WcfServiceDeficiency.IServiceDeficiency {
        
        public ServiceDeficiencyClient() {
        }
        
        public ServiceDeficiencyClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceDeficiencyClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDeficiencyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDeficiencyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.DateTime GetServerDate() {
            return base.Channel.GetServerDate();
        }
        
        public DcCommon.DB.UserData Login(string loginid, string password) {
            return base.Channel.Login(loginid, password);
        }
        
        public bool LogoutUser(CIsl.DB.WingDAC.MsUser user) {
            return base.Channel.LogoutUser(user);
        }
        
        public DcCommon.DB.DAC.DcAttachment DcAttachment_DownloadAttachment(int attachment_id) {
            return base.Channel.DcAttachment_DownloadAttachment(attachment_id);
        }
        
        public DcCommon.DB.PSCInspectionData PSCInspectionData_GetDataByCommentItemID(int comment_item_id) {
            return base.Channel.PSCInspectionData_GetDataByCommentItemID(comment_item_id);
        }
        
        public bool PSCInspectionData_InsertList(DcCommon.DB.CommentData comhead, System.Collections.Generic.List<DcCommon.DB.PSCInspectionData> datalist, CIsl.DB.WingDAC.MsUser requser) {
            return base.Channel.PSCInspectionData_InsertList(comhead, datalist, requser);
        }
        
        public System.Collections.Generic.List<DcCommon.DB.PSCInspectionData> PSCInspectionData_GetDataListBySearchData(DcCommon.DB.DAC.Search.PscInspectionSearchData sdata) {
            return base.Channel.PSCInspectionData_GetDataListBySearchData(sdata);
        }
        
        public bool PSCInspectionData_UpdateWithSister(DcCommon.DB.CommentData comhead, DcCommon.DB.PSCInspectionData pscdata, CIsl.DB.WingDAC.MsUser requser) {
            return base.Channel.PSCInspectionData_UpdateWithSister(comhead, pscdata, requser);
        }
        
        public bool PSCInspectionData_Delete(int comment_item_id, CIsl.DB.WingDAC.MsUser requser) {
            return base.Channel.PSCInspectionData_Delete(comment_item_id, requser);
        }
        
        public bool DcCiPscInspection_UpdateStatus(System.Collections.Generic.List<DcCommon.DB.DAC.DcCiPscInspection> psclist, CIsl.DB.WingDAC.MsUser requser) {
            return base.Channel.DcCiPscInspection_UpdateStatus(psclist, requser);
        }
        
        public System.Collections.Generic.List<DcCommon.DB.DAC.DcAttachment> DcAttachment_GetARecrodsAllByCommentItemID(int comment_item_id) {
            return base.Channel.DcAttachment_GetARecrodsAllByCommentItemID(comment_item_id);
        }
        
        public System.Collections.Generic.List<DcCommon.DB.DAC.DcAccident> DcAccident_GetRecordsBySearchData(DcCommon.DB.DAC.Search.AccidentSearchData sdata) {
            return base.Channel.DcAccident_GetRecordsBySearchData(sdata);
        }
        
        public DcCommon.DB.AccidentData AccidentData_GetDataByAccidentID(int accident_id) {
            return base.Channel.AccidentData_GetDataByAccidentID(accident_id);
        }
        
        public int AccidentData_InsertData(DcCommon.DB.AccidentData data, CIsl.DB.WingDAC.MsUser requser) {
            return base.Channel.AccidentData_InsertData(data, requser);
        }
        
        public bool AccidentData_UpdateData(DcCommon.DB.AccidentData data, CIsl.DB.WingDAC.MsUser requser) {
            return base.Channel.AccidentData_UpdateData(data, requser);
        }
        
        public bool AccidentData_DeleteData(int accident_id, CIsl.DB.WingDAC.MsUser requser) {
            return base.Channel.AccidentData_DeleteData(accident_id, requser);
        }
        
        public bool DcAccident_UpdateStatus(System.Collections.Generic.List<DcCommon.DB.DAC.DcAccident> aclist, CIsl.DB.WingDAC.MsUser requser) {
            return base.Channel.DcAccident_UpdateStatus(aclist, requser);
        }
        
        public string CreateAccidentReportNo() {
            return base.Channel.CreateAccidentReportNo();
        }
        
        public System.Collections.Generic.List<DcCommon.DB.DAC.DcAttachment> DcAttachment_GetARecrodsAllByAccidentID(int accident_id) {
            return base.Channel.DcAttachment_GetARecrodsAllByAccidentID(accident_id);
        }
        
        public System.Collections.Generic.List<DcCommon.DB.MoiData> MoiData_GetDataListBySearchData(DcCommon.DB.DAC.Search.MoiSearchData sdata) {
            return base.Channel.MoiData_GetDataListBySearchData(sdata);
        }
        
        public int Moi_Insert(DcCommon.DB.MoiHeaderData hdata, System.Collections.Generic.List<DcCommon.DB.MoiObservationData> obslist, CIsl.DB.WingDAC.MsUser requser) {
            return base.Channel.Moi_Insert(hdata, obslist, requser);
        }
        
        public DcCommon.DB.MoiData MoiData_GetDataByMoiObservationID(int moi_observation_id) {
            return base.Channel.MoiData_GetDataByMoiObservationID(moi_observation_id);
        }
        
        public System.Collections.Generic.List<DcCommon.DB.DAC.DcAttachment> DcAttachment_GetARecrodsAllByMoi(int moi_observation_id) {
            return base.Channel.DcAttachment_GetARecrodsAllByMoi(moi_observation_id);
        }
        
        public bool MoiData_UpdatetData(DcCommon.DB.MoiData data, CIsl.DB.WingDAC.MsUser requser) {
            return base.Channel.MoiData_UpdatetData(data, requser);
        }
        
        public bool MoiData_DeleteData(int moi_observation_id, CIsl.DB.WingDAC.MsUser requser) {
            return base.Channel.MoiData_DeleteData(moi_observation_id, requser);
        }
        
        public bool DcMoiObservation_UpdateStatus(System.Collections.Generic.List<DcCommon.DB.DAC.DcMoiObservation> obslist, CIsl.DB.WingDAC.MsUser requser) {
            return base.Channel.DcMoiObservation_UpdateStatus(obslist, requser);
        }
        
        public byte[] GetAccidentExcelTemplate() {
            return base.Channel.GetAccidentExcelTemplate();
        }
        
        public System.Collections.Generic.List<DcCommon.Output.AccidentOutputData> GetAccidentOutputData(DcCommon.Output.AccidentOutputParameter param) {
            return base.Channel.GetAccidentOutputData(param);
        }
        
        public System.Collections.Generic.List<DcCommon.DB.DAC.DcSchedulePlan> DcSchedulePlan_GetRecordsBySearchData(DcCommon.DB.DAC.Search.SchedulePlanSearchData sdata) {
            return base.Channel.DcSchedulePlan_GetRecordsBySearchData(sdata);
        }
        
        public bool DcSchedulePlan_InsertUpdateList(System.Collections.Generic.List<DcCommon.DB.DAC.DcSchedulePlan> datalist, CIsl.DB.WingDAC.MsUser requser) {
            return base.Channel.DcSchedulePlan_InsertUpdateList(datalist, requser);
        }
        
        public System.Collections.Generic.List<DcCommon.DB.DAC.DcScheduleCompany> DcScheduleCompany_GetRecordsBySearchData(DcCommon.DB.DAC.Search.ScheduleCompanySearchData sdata) {
            return base.Channel.DcScheduleCompany_GetRecordsBySearchData(sdata);
        }
        
        public System.Collections.Generic.List<DcCommon.DB.DAC.DcScheduleOther> DcScheduleOther_GetRecordsBySearchData(DcCommon.DB.DAC.Search.ScheduleOtherSearchData sdata) {
            return base.Channel.DcScheduleOther_GetRecordsBySearchData(sdata);
        }
        
        public bool DcScheduleCompany_InsertUpdateList(System.Collections.Generic.List<DcCommon.DB.DAC.DcScheduleCompany> datalist, CIsl.DB.WingDAC.MsUser requser) {
            return base.Channel.DcScheduleCompany_InsertUpdateList(datalist, requser);
        }
        
        public bool DcScheduleOther_InsertUpdateList(System.Collections.Generic.List<DcCommon.DB.DAC.DcScheduleOther> datalist, CIsl.DB.WingDAC.MsUser requser) {
            return base.Channel.DcScheduleOther_InsertUpdateList(datalist, requser);
        }
        
        public DcCommon.Output.PscOutputData GetPSCOutputData(DcCommon.Output.PscOutputParameter param) {
            return base.Channel.GetPSCOutputData(param);
        }
        
        public byte[] GetPSCExcelTemplate() {
            return base.Channel.GetPSCExcelTemplate();
        }
        
        public byte[] GetMoiExcelCategoryTemplate() {
            return base.Channel.GetMoiExcelCategoryTemplate();
        }
        
        public byte[] GetMoiExcelListTemplate() {
            return base.Channel.GetMoiExcelListTemplate();
        }
        
        public byte[] GetMoiReportCommentListTemplate() {
            return base.Channel.GetMoiReportCommentListTemplate();
        }
        
        public byte[] GetMoiReportObservationTemplate() {
            return base.Channel.GetMoiReportObservationTemplate();
        }
        
        public DcCommon.Output.MoiExcelOutputDataCategory GetMoiExcelDataCategory(DcCommon.Output.MoiExcelOutputParameter param) {
            return base.Channel.GetMoiExcelDataCategory(param);
        }
        
        public DcCommon.Output.MoiExcelOutputDataCategory GetMoiExcelDataCategory2(DcCommon.Output.MoiExcelOutputParameter param, CIsl.DB.WingDAC.MsViqVersion version) {
            return base.Channel.GetMoiExcelDataCategory2(param, version);
        }
        
        public byte[] GetScheduleListTemplateFile() {
            return base.Channel.GetScheduleListTemplateFile();
        }
        
        public System.Collections.Generic.List<CIsl.DB.WingDAC.MsVessel> MsVessel_GetRecords() {
            return base.Channel.MsVessel_GetRecords();
        }
        
        public System.Collections.Generic.List<CIsl.DB.WingDAC.MsUser> MsUser_GetRecords() {
            return base.Channel.MsUser_GetRecords();
        }
        
        public DcCommon.DB.UserData UserData_GetDataByMsUserID(string ms_user_id) {
            return base.Channel.UserData_GetDataByMsUserID(ms_user_id);
        }
        
        public System.Collections.Generic.List<CIsl.DB.WingDAC.MsItemKind> MsItemKind_GetRecords() {
            return base.Channel.MsItemKind_GetRecords();
        }
        
        public System.Collections.Generic.List<DcCommon.DB.DAC.MsStatus> MsStatus_GetRecords() {
            return base.Channel.MsStatus_GetRecords();
        }
        
        public System.Collections.Generic.List<DcCommon.DB.DAC.MsAlarmColor> MsAlarmColor_GetRecords() {
            return base.Channel.MsAlarmColor_GetRecords();
        }
        
        public System.Collections.Generic.List<CIsl.DB.WingDAC.MsActionCode> MsActionCode_GetRecords() {
            return base.Channel.MsActionCode_GetRecords();
        }
        
        public System.Collections.Generic.List<CIsl.DB.WingDAC.MsDeficiencyCode> MsDeficiencyCode_GetRecords() {
            return base.Channel.MsDeficiencyCode_GetRecords();
        }
        
        public System.Collections.Generic.List<CIsl.DB.WingDAC.MsVesselType> MsVesselType_GetRecords() {
            return base.Channel.MsVesselType_GetRecords();
        }
        
        public System.Collections.Generic.List<CIsl.DB.WingDAC.MsBasho> MsBasho_GetRecords() {
            return base.Channel.MsBasho_GetRecords();
        }
        
        public System.Collections.Generic.List<CIsl.DB.WingDAC.MsRegional> MsRegional_GetRecords() {
            return base.Channel.MsRegional_GetRecords();
        }
        
        public int MsAlarmColor_InsertRecord(DcCommon.DB.DAC.MsAlarmColor data, CIsl.DB.WingDAC.MsUser requser) {
            return base.Channel.MsAlarmColor_InsertRecord(data, requser);
        }
        
        public bool MsAlarmColor_UpdateRecord(DcCommon.DB.DAC.MsAlarmColor data, CIsl.DB.WingDAC.MsUser requser) {
            return base.Channel.MsAlarmColor_UpdateRecord(data, requser);
        }
        
        public bool MsAlarmColor_DeleteRecord(DcCommon.DB.DAC.MsAlarmColor data, CIsl.DB.WingDAC.MsUser requser) {
            return base.Channel.MsAlarmColor_DeleteRecord(data, requser);
        }
        
        public System.Collections.Generic.List<CIsl.DB.WingDAC.MsAccidentImportance> MsAccidentImportance_GetRecords() {
            return base.Channel.MsAccidentImportance_GetRecords();
        }
        
        public System.Collections.Generic.List<CIsl.DB.WingDAC.MsAccidentKind> MsAccidentKind_GetRecords() {
            return base.Channel.MsAccidentKind_GetRecords();
        }
        
        public System.Collections.Generic.List<CIsl.DB.WingDAC.MsAccidentSituation> MsAccidentSituation_GetRecords() {
            return base.Channel.MsAccidentSituation_GetRecords();
        }
        
        public System.Collections.Generic.List<DcCommon.DB.DAC.MsAccidentStatus> MsAccidentStatus_GetRecords() {
            return base.Channel.MsAccidentStatus_GetRecords();
        }
        
        public System.Collections.Generic.List<CIsl.DB.WingDAC.MsKindOfAccident> MsKindOfAccident_GetRecords() {
            return base.Channel.MsKindOfAccident_GetRecords();
        }
        
        public System.Collections.Generic.List<CIsl.DB.WingDAC.MsInspectionCategory> MsInspectionCategory_GetRecords() {
            return base.Channel.MsInspectionCategory_GetRecords();
        }
        
        public System.Collections.Generic.List<CIsl.DB.WingDAC.MsViqCode> MsViqCode_GetRecords() {
            return base.Channel.MsViqCode_GetRecords();
        }
        
        public System.Collections.Generic.List<CIsl.DB.WingDAC.MsViqNo> MsViqNo_GetRecords() {
            return base.Channel.MsViqNo_GetRecords();
        }
        
        public System.Collections.Generic.List<CIsl.DB.WingDAC.MsViqNo> MsViqNo_GetRecordsByViqCodeID(int viq_code_id) {
            return base.Channel.MsViqNo_GetRecordsByViqCodeID(viq_code_id);
        }
        
        public System.Collections.Generic.List<DcCommon.DB.DAC.MsMoiStatus> MsMoiStatus_GetRecords() {
            return base.Channel.MsMoiStatus_GetRecords();
        }
        
        public System.Collections.Generic.List<CIsl.DB.WingDAC.MsCustomer> MsCustomer_GetRecords() {
            return base.Channel.MsCustomer_GetRecords();
        }
        
        public System.Collections.Generic.List<CIsl.DB.WingDAC.MsCustomer> MsCustomer_GetRecordsInspectionCompany() {
            return base.Channel.MsCustomer_GetRecordsInspectionCompany();
        }
        
        public System.Collections.Generic.List<CIsl.DB.WingDAC.MsCustomer> MsCustomer_GetRecordsAppointedCompany() {
            return base.Channel.MsCustomer_GetRecordsAppointedCompany();
        }
        
        public System.Collections.Generic.List<CIsl.DB.WingDAC.MsDeficiencyCategory> MsDeficiencyCategory_GetRecords() {
            return base.Channel.MsDeficiencyCategory_GetRecords();
        }
        
        public System.Collections.Generic.List<DcCommon.DB.DAC.MsYear> MsYear_GetRecords() {
            return base.Channel.MsYear_GetRecords();
        }
        
        public System.Collections.Generic.List<CIsl.DB.WingDAC.MsScheduleCategory> MsScheduleCategory_GetRecords() {
            return base.Channel.MsScheduleCategory_GetRecords();
        }
        
        public System.Collections.Generic.List<CIsl.DB.WingDAC.MsScheduleKind> MsScheduleKind_GetRecords() {
            return base.Channel.MsScheduleKind_GetRecords();
        }
        
        public System.Collections.Generic.List<CIsl.DB.WingDAC.MsScheduleKindDetail> MsScheduleKindDetail_GetRecords() {
            return base.Channel.MsScheduleKindDetail_GetRecords();
        }
        
        public System.Collections.Generic.List<DcCommon.DB.DeficiencyCategoryData> DeficiencyCategoryData_GetDataList() {
            return base.Channel.DeficiencyCategoryData_GetDataList();
        }
        
        public System.Collections.Generic.List<CIsl.DB.WingDAC.MsViqCodeName> MsViqCodeName_GetRecords() {
            return base.Channel.MsViqCodeName_GetRecords();
        }
        
        public System.Collections.Generic.List<CIsl.DB.WingDAC.MsViqVersion> MsViqVersion_GetRecords() {
            return base.Channel.MsViqVersion_GetRecords();
        }
        
        public System.Collections.Generic.List<CIsl.DB.WingDAC.MsVesselScheduleKindDetailEnable> MsVesselScheduleKindDetailEnable_GetRecordsByMsVesselID(decimal ms_vessel_id) {
            return base.Channel.MsVesselScheduleKindDetailEnable_GetRecordsByMsVesselID(ms_vessel_id);
        }
        
        public System.Collections.Generic.List<CIsl.DB.WingDAC.MsVesselScheduleKindDetailEnable> MsVesselScheduleKindDetailEnable_GetRecords() {
            return base.Channel.MsVesselScheduleKindDetailEnable_GetRecords();
        }
        
        public System.Collections.Generic.List<CIsl.DB.WingDAC.MsVesselCategory> MsVesselCategory_GetRecords() {
            return base.Channel.MsVesselCategory_GetRecords();
        }
        
        public System.Collections.Generic.List<CIsl.DB.WingDAC.MsCrewMatrixType> MsCrewMatrixType_GetRecords() {
            return base.Channel.MsCrewMatrixType_GetRecords();
        }
    }
}
